### ISSUE TITLE
unsigned char to fix right shift

### ISSUE THREAD

**Issue by milahu** [plageoj/urlencode#1]
https://github.com/plageoj/urlencode/blob/3ff1c5a59b04bfd719267735761d38273558657d/src/UrlEncode.h#L11

should be

```c
 inline String urlEncode(const unsigned char *msg) 
```

to fix

https://github.com/plageoj/urlencode/blob/3ff1c5a59b04bfd719267735761d38273558657d/src/UrlEncode.h#L25

https://stackoverflow.com/questions/23176797/right-bit-shift-giving-wrong-result-can-someone-explain

**Comment by plageoj** [comment]
@milahu Thank you for reporting I will fix it.
